up

diff --git a/.github/workflows/pipline.yml b/.github/workflows/pipline.yml
--- a/.github/workflows/pipline.yml
+++ b/.github/workflows/pipline.yml
@@ -31,22 +31,20 @@ jobs:
               run: |
                     mkdir -p test-reports
                     npm test -- --json --outputFile=test-reports/test-report.json
-                    echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
-              continue-on-error: true  # Ensure the workflow continues after test failure
+              continue-on-error: true 
 
             - name: Upload test report as artifact
               uses: actions/upload-artifact@v4
               with:
                 name: test-report
                 path: test-reports/test-report.json
-
-            - name: "Fail workflow if tests failed"
+            
+            - name: Check test results and fail if tests failed
               run: |
-                if [ "$TEST_EXIT_CODE" -ne 0 ]; then
-                  echo "Tests failed, failing the workflow"
-                  exit 1
-                fi
-
+                  if grep -q '"failed": [1-9]' test-reports/test-report.json; then
+                      echo "Unit tests failed!"
+                      exit 1
+                  fi
     build_and_push:
         runs-on: ubuntu-latest
         needs: [ "unit_testing_job", "code_analysis_job" ]
